---
- name: Apply system kernel parameters
  ansible.posix.sysctl:
    name: "{{ parameter.key }}"
    value: "{{ parameter.value }}"
    sysctl_file: /etc/sysctl.d/99-custom.conf
    state: present
    reload: true
  loop: "{{ system_sysctl | dict2items }}"
  loop_control:
    loop_var: parameter
  become: true
