---
- name: Create NUT UPSSCHED run directory
  ansible.builtin.file:
    path: "{{ nut_upssched_run_dir }}"
    state: directory
    owner: nut
    group: nut
    mode: "0770"
  become: true

- name: Deploy NUT UPSSCHED CMD script
  ansible.builtin.template:
    src: upssched-cmd
    dest: /usr/local/sbin/upssched-cmd
    owner: root
    group: nut
    mode: "0750"
  become: true

- name: Deploy NUT UPSSCHED configuration
  ansible.builtin.template:
    src: upssched.conf
    dest: "{{ nut_dir }}/upssched.conf"
    owner: root
    group: nut
    mode: "0640"
  become: true
